### ISSUE TITLE
New fragment file from cellranger-atac-2?

### ISSUE THREAD

**Issue by cnk113** [GreenleafLab/brainchromatin#9]
Hello,

I was wondering if you can realign the scATAC-seq data using the newest version of cellranger atac since the deduplication has changed the output fragments significantly (better)?

Best,
Chang

**Comment by cnk113** [comment]
Sorry I should clarify, the newest cellranger arc version which has the latest changes from the cellranger-atac-2 algorithmic changes.

**Comment by demuellae** [comment]
Hi Chang,
We reprocessed the data using CellRangerARC 2. You can find the ATAC fragment files here:
https://muellerf.s3.amazonaws.com/data/projects/BrainDev/fragments_multiome_ctx_cellrangerarc2/atac_fragments.tar.gz

Hope this helps

**Comment by cnk113** [comment]
Hey Fabian, 

Can I also get unfiltered and filtered peak matrix from the ARC run?

Thanks,
Chang

**Comment by demuellae** [comment]
Sure, here you go:
https://muellerf.s3.amazonaws.com/data/projects/BrainDev/fragments_multiome_ctx_cellrangerarc2/peakM.tar.gz

**Comment by vitkl** [comment]
Hi @demuellae 

Thanks for sharing this!

Does this file https://muellerf.s3.amazonaws.com/data/projects/BrainDev/fragments_multiome_ctx_cellrangerarc2/atac_fragments.tar.gz include the data from all 3 multiome samples?

Are the files here similarly up-to-date? https://github.com/GreenleafLab/brainchromatin/blob/main/links.txt
